name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: "Publish release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: "Install dependancies"
        run: |
          python -m pip install --upgrade pip setuptools
          pip install --upgrade twine wheel
      - name: "Build package"
        run: |
          python setup.py sdist bdist_wheel
      - name: "Publish to PyPI"
        run: |
          twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
